spring:
  config:
    activate:
      on-profile: dev
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:postgresql://localhost:5434/wheel_wander_db
    username: wheel_wander
    password: secret

server:
  port: 9001
---
spring:
  config:
    activate:
      on-profile: testing
server:
  port: 9002